#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

 // Define names for your custom tap dances
enum {
    TD_E_ACCENT = 0
};

// Define what happens on each tap count
void dance_e_finished(tap_dance_state_t *state, void *user_data) {
    if (state->count == 1) {
        // Single tap: send standard 'e'
        register_code16(KC_E);
    } else if (state->count == 2) {
        // Double tap: send 'é'
        // (Alternatively, use unicode or a specific macro if SEND_STRING doesn't match your layout)
        send_string("é");
    }
}

void dance_e_reset(tap_dance_state_t *state, void *user_data) {
    if (state->count == 1) {
        unregister_code16(KC_E);
    }
}

// Register the tap dance in QMK's tap dance structure
tap_dance_action_t tap_dance_actions[] = {
    [TD_E_ACCENT] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, dance_e_finished, dance_e_reset),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ortho_4x12(LT(5,KC_ESC), KC_SCLN, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_QUOT, KC_TAB, KC_A, KC_O, TD(TD_E_ACCENT), KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_ENT, KC_LSFT, KC_Z, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_SLSH, KC_RSFT, MO(7), KC_LCTL, KC_LALT, KC_LGUI, MO(3), KC_SPC, KC_BSPC, MO(4), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),
    [1] = LAYOUT_ortho_4x12(LT(5,KC_ESC), KC_SCLN, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_QUOT, KC_TAB, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_ENT, KC_LSFT, KC_Z, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_SLSH, KC_RSFT, MO(7), KC_LGUI, KC_LALT, KC_LCTL, MO(8), KC_SPC, KC_BSPC, MO(9), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),
    [2] = LAYOUT_ortho_4x12(LT(5,KC_ESC), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_QUOT, KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_ENT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, MO(7), KC_LCTL, KC_LALT, KC_LGUI, MO(3), KC_SPC, KC_BSPC, MO(4), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),
    [3] = LAYOUT_ortho_4x12(KC_F12, KC_F2, KC_F3, KC_F4, KC_NO, KC_NO, KC_NO, KC_LPRN, KC_RPRN, KC_NO, KC_NO, RCS(KC_GRV), LSFT(KC_F12), LCA(KC_K), RCS(KC_2), RCS(KC_F), LCTL(KC_F), LCA(KC_F), LCA(KC_G), KC_LBRC, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_TRNS, LCA(KC_J), LCA(KC_L), LCTL(KC_C), LCTL(KC_V), LCA(KC_P), LCA(KC_Y), KC_LCBR, KC_RCBR, KC_NO, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LGUI, KC_TRNS, RAG(KC_J), RCS(KC_K), MO(6), KC_HOME, KC_PGDN, KC_PGUP, KC_END),
    [4] = LAYOUT_ortho_4x12(KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, LCTL(KC_T), RCS(KC_O), LCTL(KC_P), LCA(KC_TAB), LGUI(KC_1), LGUI(KC_2), RCS(KC_P9), RCS(KC_P3), LGUI(KC_8), LGUI(KC_9), KC_UNDS, KC_MINS, KC_EQL, KC_PLUS, KC_F1, KC_CAPS, LGUI(KC_3), LGUI(KC_4), LGUI(KC_5), LGUI(KC_6), LGUI(KC_7), KC_RCTL, LCTL(KC_GRV), RCS(KC_U), RCS(KC_M), RCS(KC_Y), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(6), KC_TRNS, KC_DEL, KC_TRNS, RCS(KC_E), RCS(KC_QUOT), RCS(KC_D), LCA(KC_QUOT)),
    [5] = LAYOUT_ortho_4x12(KC_TRNS, KC_F10, KC_F11, LSFT(KC_F11), KC_F5, RCS(KC_F5), KC_NO, KC_P7, KC_P8, KC_P9, KC_NO, KC_NO, KC_TRNS, KC_F6, KC_F7, KC_F8, KC_F9, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, KC_MINS, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_SLSH, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_SPC, KC_BSPC, KC_P0, KC_PDOT, KC_NO, KC_NO, KC_NUM),
    [6] = LAYOUT_ortho_4x12(KC_TRNS, QK_BOOT, DB_TOGG, UG_TOGG, UG_NEXT, UG_HUEU, UG_HUED, UG_SATU, UG_SATD, UG_VALU, UG_VALD, KC_DEL, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, DF(0), DF(1), DF(2), KC_TRNS, KC_TRNS, KC_TRNS, RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_SW, RGB_M_SN, RGB_M_K, RGB_M_X, RGB_M_G, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [7] = LAYOUT_ortho_4x12(KC_NO, KC_BRID, KC_BRIU, KC_NO, KC_NO, KC_MPRV, KC_MPLY, KC_MNXT, KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, LSG(KC_4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MS_LEFT, MS_DOWN, MS_UP, MS_RGHT, KC_NO, KC_PSCR, MS_BTN3, MS_BTN2, MS_BTN1, KC_NO, KC_NO, KC_NO, KC_NO, MS_WHLL, MS_WHLD, MS_WHLU, MS_WHLR, KC_TRNS, MS_ACL0, MS_ACL1, MS_ACL2, KC_NO, KC_NO, KC_NO, KC_NO, MS_LEFT, MS_DOWN, MS_UP, MS_RGHT),
    [8] = LAYOUT_ortho_4x12(KC_F12, KC_F2, KC_F3, KC_F4, KC_NO, KC_NO, KC_NO, KC_LPRN, KC_RPRN, KC_NO, KC_NO, RCS(KC_GRV), LSFT(KC_F12), LCA(KC_K), RCS(KC_2), RCS(KC_F), LGUI(KC_F), LCA(KC_F), LCA(KC_G), KC_LBRC, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_TRNS, LCA(KC_J), LCA(KC_L), LGUI(KC_C), LGUI(KC_V), LCA(KC_P), LCA(KC_Y), KC_LCBR, KC_RCBR, KC_NO, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LGUI, KC_TRNS, RAG(KC_J), RCS(KC_K), MO(6), KC_HOME, KC_PGDN, KC_PGUP, KC_END),
    [9] = LAYOUT_ortho_4x12(KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, LCTL(KC_T), RCS(KC_O), LCTL(KC_P), LCA(KC_TAB), LGUI(KC_1), LGUI(KC_2), RCS(KC_P9), RCS(KC_P3), LGUI(KC_8), LGUI(KC_9), KC_UNDS, KC_MINS, KC_EQL, KC_PLUS, KC_F1, KC_CAPS, LGUI(KC_3), LGUI(KC_4), LGUI(KC_5), LGUI(KC_6), LGUI(KC_7), KC_RCTL, LCTL(KC_GRV), RCS(KC_U), RCS(KC_M), RCS(KC_Y), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(6), KC_TRNS, KC_DEL, KC_TRNS, RCS(KC_E), RCS(KC_QUOT), RCS(KC_D), LCA(KC_QUOT))
};




#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
